using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MusicZon : MonoBehaviour
{
    public AudioSource audioSource;
    public float fadeTime;
    public float maxVolume;
    private float targetVolume;
    void Start()
    {
        targetVolume = 0;
        audioSource = GetComponent<AudioSource>();
        audioSource.volume = targetVolume;
        audioSource.Play();
    }

    void Update()
    {
        if(!Mathf.Approximately(audioSource.volume, targetVolume))
        {
            audioSource.volume = Mathf.MoveTowards(audioSource.volume, targetVolume, (maxVolume / fadeTime) * Time.deltaTime);
        }    
    }

    private void OnTrigger(Collider other)
    {
        if(other.CompareTag("Player"))
        {
            targetVolume = 0f;
        }
    }
}
